// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABIfYviXUHSfaJnH888N4nWJb8I4JmUUA',
    appId: '1:1010543661123:web:2da637a7fe5823416a44f6',
    messagingSenderId: '1010543661123',
    projectId: 'chat-room-c29a7',
    authDomain: 'chat-room-c29a7.firebaseapp.com',
    storageBucket: 'chat-room-c29a7.firebasestorage.app',
    measurementId: 'G-C4E69C7JN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb9p8PrJtld_b5PFwNb76ET53rQlJRkFE',
    appId: '1:1010543661123:android:f405b405b00ceea66a44f6',
    messagingSenderId: '1010543661123',
    projectId: 'chat-room-c29a7',
    storageBucket: 'chat-room-c29a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJYs5EYgtLaTzp5XrDTY5Z9yJh_AOGKaw',
    appId: '1:1010543661123:ios:b51f7ad4151418d86a44f6',
    messagingSenderId: '1010543661123',
    projectId: 'chat-room-c29a7',
    storageBucket: 'chat-room-c29a7.firebasestorage.app',
    iosBundleId: 'com.example.chatRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJYs5EYgtLaTzp5XrDTY5Z9yJh_AOGKaw',
    appId: '1:1010543661123:ios:b51f7ad4151418d86a44f6',
    messagingSenderId: '1010543661123',
    projectId: 'chat-room-c29a7',
    storageBucket: 'chat-room-c29a7.firebasestorage.app',
    iosBundleId: 'com.example.chatRoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABIfYviXUHSfaJnH888N4nWJb8I4JmUUA',
    appId: '1:1010543661123:web:80a600e0074453f96a44f6',
    messagingSenderId: '1010543661123',
    projectId: 'chat-room-c29a7',
    authDomain: 'chat-room-c29a7.firebaseapp.com',
    storageBucket: 'chat-room-c29a7.firebasestorage.app',
    measurementId: 'G-CE2VQ2HZHN',
  );
}
